# Basic Site settings
title: WinForge
description: The ultimate Windows 11 optimization toolkit.
url: "https://mrdarksidetm.github.io"
baseurl: ""  # For /docs source

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: <!-- more -->

# Plugins (matches Gemfile)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

# Indigo Theme (remote)
remote_theme: sergiokopplin/indigo
paginate: 5
paginate_path: /page:num/

# Exclude (prevents upload issues)
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
