# Site settings
title: WinForge
tagline: Windows 11 Optimization Toolkit
email: mrdarksidetm@example.com  # Update with yours
description: >
  The ultimate PowerShell script for debloating, customizing, and optimizing Windows 11 for performance, privacy, and minimalism.
baseurl: ""
url: "https://mrdarksidetm.github.io"

# Build settings
markdown: kramdown
permalink: /:title/
excerpt_separator: ""
lsi: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate-v2
  - jekyll-seo-tag  # Fixes {% seo %} tag error

# Theme
remote_theme: sergiokopplin/indigo

# Author (for SEO, sidebar, footer)
author:
  name: MrDarksideTM
  url: https://github.com/mrdarksidetm
  email: mrdarksidetm@example.com  # Update
  picture: /assets/images/profile.jpg  # Optional: add photo
  twitter: mrdarksidetm  # Optional
  github: mrdarksidetm

# Pagination v2 (for posts on homepage)
pagination:
  enabled: true
  collection: 'posts'
  sort_field: 'date'
  sort_reverse: true
  per_page: 5
  permalink: '/page/:num/'
  extension: none
  indexpage: 'index.html'  # Or .md
  title: ':title - page :num of :max'

# SEO defaults (jekyll-seo-tag uses these)
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
      author_profile: false
      read_time: false

# Collections (for projects/releases if needed)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Exclude (prevents bloat in _site)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .gitignore
  - .editorconfig
