# Site settings
title: WinForge
description: Windows 11 Optimization Tool
url: "https://mrdarksidetm.github.io"
baseurl: "/WinForge"

# Theme (remote GitHub repo)
remote_theme: sergiokopplin/indigo

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag

# Pagination (v3.0+ compat)
pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  title: " - Page :num"  # Replaces deprecated title_suffix

# Sass config to suppress deprecations (via jekyll-sass-converter)
sass:
  style: compressed
  quiet_deps: true
  silence_deprecations: ['import']
  incremental: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
