source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "webrick", "~> 1.8"

# Remote theme support
gem "jekyll-remote-theme"

# Pagination v2 (fixes legacy error)
gem "jekyll-paginate-v2", "~> 3.0"

# Markdown & syntax highlighting
gem "kramdown-parser-gfm"
gem "rouge"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-redirect-from"
end

# Windows and JRuby does not include zoneinfo-data
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
