source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-sass-converter", "~> 3.1.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-paginate-v2", github: "sverrirs/jekyll-paginate-v2"
  gem "jekyll-sitemap", "~> 1.4"
  gem "jekyll-seo-tag", "~> 2.8"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Windows file watcher for faster auto-regen (avoids polling)
platforms :mingw, :mswin, :x64_mingw, :jruby do
  gem "wdm", ">= 0.1.0"
end
