name: Deploy Jekyll with Tailwind

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node for Tailwind build
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Deterministic npm install
      - name: Install dependencies
        run: npm ci

      # Optional: Silence Browserslist warning
      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      # Build Tailwind via package.json script
      - name: Build Tailwind CSS
        run: npm run build:css

      # Ruby/Jekyll for Pages (Gemfile is in ./docs)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Bundle install (docs)
        working-directory: ./docs
        run: bundle install --path vendor/bundle

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll (docs -> _site)
        working-directory: ./docs
        run: bundle exec jekyll build --destination ../_site
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
